services:
  springboot:
    build: .
    image: olsohee/funfit_community:latest
    container_name: funfit_community
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
